### ISSUE TITLE
Does it only work in shell?

### ISSUE THREAD

**Issue by ralyodio** [mattlubner/qr-decode-encode#17]
What about node/browser or Deno?

**Comment by ralyodio** [comment]
I tried this but it fails due to jimp not exporting `read`

```
$ deno install -qAf --unstable 'https://cdn.skypack.dev/-/qr-decode-encode@v1.1.0-9KLw3N6NEJWF2QR6if80/dist=es2019,mode=imports/optimized/qr-decode-encode.js'
Warning Implicitly using latest version (0.115.1) for https://deno.land/std/node/fs.ts
Warning Implicitly using latest version (0.115.1) for https://deno.land/std/node/string_decoder.ts
error: Uncaught SyntaxError: The requested module '/-/jimp@v0.16.1-pG3SG6O9IUH0kDNb5IZv/dist=es2019,mode=imports/optimized/jimp.js' does not provide an export named 'read'
    at <anonymous> (https://cdn.skypack.dev/-/javascript-barcode-reader@v0.6.9-aSmtrWMmNUBwZNqnTEjG/dist=es2019,mode=imports/optimized/javascript-barcode-reader.js:1:9)
```

**Comment by ralyodio** [comment]
I think you need to upgrade to latest jimp....they added a fix so jimp exports properly.

**Comment by mattlubner** [comment]
Should work in node, haven't tested in Deno. For the browser, it's probably best to use Jimp or javascript-barcode-reader directly.

Doesn't look like Jimp 0.16.2 is published as "latest" yet – it's still considered a canary approach. More than happy to update, once that's stable.

**Comment by mattlubner** [comment]
I'm going to close this. There doesn't appear to be any `jimp` update, and the original goal/scope of the project is as a shell helper utility.
